// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.thebytecloud.greeting;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greeting.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
