// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface ComputeAverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.ComputeAverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
