// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface FindMaxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.FindMaxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 response = 1;</code>
   */
  int getResponse();
}
