// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface PrimeNumberDecompositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.PrimeNumberDecompositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 prime_factor = 1;</code>
   */
  long getPrimeFactor();
}
