// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface PrimeNumberDecompositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.PrimeNumberDecompositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   */
  long getNumber();
}
