// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum_result = 1;</code>
   */
  int getSumResult();
}
