// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.thebytecloud.calculator;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 first_number = 1;</code>
   */
  int getFirstNumber();

  /**
   * <code>int32 second_number = 2;</code>
   */
  int getSecondNumber();
}
